service: TestProject

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  rateHandler:
    handler: newman.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(5 minutes)